query getCarbonRepoList {
  # Let's use carbon as our organization
  organization(login: "carbon-design-system") {
    # We'll grab all the repositories in one go. To load more resources
    # continuously, see the advanced topics.
    repositories(first: 75, orderBy: { field: UPDATED_AT, direction: DESC }) {
      totalCount
      nodes {
        url
        homepageUrl
        issues(filterBy: { states: OPEN }) {
          totalCount
        }
        stargazers {
          totalCount
        }
        releases(first: 1) {
          totalCount
          nodes {
            name
          }
        }
        name
        updatedAt
        createdAt
        description
        id
      }
    }
  }
}
