nodeLinker: node-modules

yarnPath: '.yarn/releases/yarn-berry.cjs'
enableGlobalCache: true
enableTelemetry: false
enableStrictSsl: false
npmScopes:
  repo:
    npmRegistryServer: https://nexus.icc/repository/npm/
    npmPublishRegistry: https://nexus.icc/repository/npm/
